"""
groupCall.py — batch orchestrator for generateShortRead.py.

This is the driver most experiments were launched through. It reads a list
of plasmid pairs (in various file formats produced at different stages of
the project) and fans out calls to `generateShortRead.py` in parallel
subprocess batches, one call per pair, so each pair's fragment-ordering
distance distribution gets computed and appended to an allDistances_*.txt
file.

The different functions below are essentially one experiment each — they
existed to point the same batching logic at a different input file or
plasmid subset (real sequencing data, synthetic rearrangements, binned
fragments, filtered subsets, etc.) as the analysis evolved. `func` (see
__main__) selects which one runs.

Data sources referenced by these functions:
  fastas/            Original full-length plasmid assemblies from the pling
                      GitHub repo. Artificially fragmented for testing since
                      short-read assembly does not yield full-length plasmids.
  syntethic/          Synthetic plasmid database generated by this project
                      (see syntethic.py) by applying random rearrangement
                      events to the fastas/ plasmids — used to get distance
                      pairs with a known ground-truth rearrangement distance.
  plasmid_references/ Reference (full-length) plasmid sequences corresponding
                      to a real short-read dataset from another paper.
  binned_fragments/   Contigs from that real short-read dataset, assigned
                      ("binned") to whichever plasmid_references/ sequence
                      they best align to (see bin_fragments.py) — this is
                      the real short-read test case, as opposed to the
                      artificially fragmented fastas/ / syntethic/ data.

CLI: python groupCall.py <func> <size> <implementation:true|false>
  func            selects which experiment function to run (0-8, see __main__)
  size            number of fragments to split each plasmid into
  implementation  "true" to use break_distance.my_implementation,
                  "false" to use pling
"""
import subprocess
import matplotlib.pyplot as plt
import numpy as np
import random as rm
import sys
from syntethic import run
from run_pling import run_pling
import os


def create_input():
	"""Builds input_syntethic.txt: one line per synthetic plasmid, pairing
	each regenerated (rearranged) file with its original in ./fastas/,
	matched by the part of the filename before the first underscore."""
	syntethic_fasta = subprocess.check_output("ls -1 ./syntethic/regenerated/",shell=True,text=True)
	syntethic_fasta = syntethic_fasta.split("\n")
	f = open("input_syntethic.txt","w+")
	for file in syntethic_fasta:
		og_fasta = file.split("_")[0]
		f.write(f"./fastas/{og_fasta} ./syntethic/regenerated/{file}\n")
	f.close()

i=0
def sample_random_plasmids():
	"""func=0. Reads plasmid pairs from uniqueDistancesv2.txt and processes
	them in an infinite loop, 10 pairs (`parralel`) per batch."""
	pair_plasmids = []
	with open("uniqueDistancesv2.txt") as f:
		for x in f:
			s = x.strip()
			pair_plasmids.append((s.split()[0][1:],s.split()[1][1:]))

	i = 0
	k = 0
	size = 6
	parallel = 10
	while True:
		plasmids_pairs = rm.sample(pair_plasmids,10)
		commands = [f"python ./generateShortRead.py {j[0]} {j[1]} {k} {index} {size} {implementation}" for index,j in enumerate(plasmids_pairs[i:i+parallel])]
		procs = [subprocess.Popen(j,shell=True) for j in commands]
		for p in procs:
			p.wait()
		print(f"The batch finished {i}")
		i+=parallel
		k+=1

def sample_continous(implementation):
	"""func=4. Reads plasmid pairs from input_syntethic.txt (see
	create_input()) and processes them in batches of 10 in parallel,
	fragmenting each plasmid into 6 pieces. Cleans up the intermediate
	py_out/ input/fasta files after each batch unless implementation=True
	(the my_implementation path needs them to persist for inspection)."""
	pair_plasmids = []
	with open("input_syntethic.txt") as f:
		for x in f:
			s = x.strip()
			pair_plasmids.append((s.split()[0][1:],s.split()[1][1:]))

	i=0
	k=0
	parralel = 10
	while i<len(pair_plasmids):
		commands = [f"python ./generateShortRead.py {j[0]} {j[1]} {k} {index} {6} {implementation}" for index,j in enumerate(pair_plasmids[i:i+parralel])]
		procs = [subprocess.Popen(j,shell=True) for j in commands]
		for p in procs:
			p.wait()
		if not implementation:
			for index,_ in enumerate(pair_plasmids[i:i+parralel]):
				subprocess.call(f"rm -r ./py_out/input{k}_{index}.txt", shell=True)
				subprocess.call(f"rm -r ./py_out/try{k}_{index}.fasta", shell=True)
		print(f"The batch finished {i}")
		i+=parralel
		k+=1

def change_fragments_known(size,implementation):
	"""func=1. Re-runs generateShortRead.py at a different fragment count
	(`size`) for the same plasmid pairs already sampled in
	allDistances_v2_1.txt — used to see how the distance distribution
	changes as the number of fragments varies, for a fixed pair set."""
	plasmid_pairs = []
	with open("allDistances_v2_1.txt") as f:
		for line in f:
			if "/" in line:
				plasmid_pairs.append(("/fastas/"+line.split("/")[2].strip(),"/fastas/"+line.split("/")[4].strip()))
	i=0
	k=0
	parralel = 1
	while i<len(plasmid_pairs):
		commands = [f"python ./generateShortRead.py {j[0]} {j[1]} {k} {index} {size} {implementation}" for index,j in enumerate(plasmid_pairs[i:i+parralel])]
		procs = [subprocess.Popen(j,shell=True) for j in commands]
		for p in procs:
			p.wait()
		if not implementation:
			for index,_ in enumerate(plasmid_pairs[i:i+parralel]):
				subprocess.call(f"rm -r ./py_out/input{k}_{index}.txt", shell=True)
				subprocess.call(f"rm -r ./py_out/try{k}_{index}.fasta", shell=True)
		print(f"The batch finished {i}")
		i+=parralel
		k+=1
#print(commands)
		#subprocess.call(f"python ./generateShortRead.py {s.split()[0][1:]} {s.split()[1][1:]} {i}", shell=True)

def sample_random_plasmids2(size,implementation):
	"""func=5. Reads plasmid pairs from unique_distances_real_final.txt,
	randomly samples 100 of them, and runs generateShortRead.py on each in
	batches of 10 — the "real data" counterpart to sample_continous()'s
	synthetic-data run."""
	plasmid_pairs = []
	with open("unique_distances_real_final.txt") as f:
		for x in f:
			s = x.strip()
			plasmid_pairs.append((s.split()[0][1:],s.split()[1][1:]))
	i=0
	k=0
	parralel = 10
	plasmid_pairs = rm.sample(plasmid_pairs,100)

	while i<len(plasmid_pairs):
		commands = [f"python ./generateShortRead.py {j[0]} {j[1]} {k} {index} {size} {implementation}" for index,j in enumerate(plasmid_pairs[i:i+parralel])]
		procs = [subprocess.Popen(j,shell=True) for j in commands]
		for p in procs:
			p.wait()
		if not implementation:
			for index,_ in enumerate(plasmid_pairs[i:i+parralel]):
				subprocess.call(f"rm -r ./py_out/input{k}_{index}.txt", shell=True)
				subprocess.call(f"rm -r ./py_out/try{k}_{index}.fasta", shell=True)
		print(f"The batch finished {i}")
		i+=parralel
		k+=1
		
def trying_something():
	"""Default/fallback branch (any func not in 0-8). One-off debug call:
	runs generateShortRead.py on just the first pair found in
	allDistances_v2_5.txt."""
	plasmid_pairs = []
	with open("allDistances_v2_5.txt") as f:
		for line in f:
			if "/" in line:
				plasmid_pairs.append(("/fastas/"+line.split("/")[2].strip(),"/fastas/"+line.split("/")[4].strip()))
	
	subprocess.call(f"python ./generateShortRead.py {plasmid_pairs[0][0]} {plasmid_pairs[0][1]} {1} {0} {5}",shell=True)

def run_syntethic(size):
	"""func=3. For every synthetic plasmid under syntethic/regenerated/,
	runs generateShortRead.py against its original counterpart in
	./fastas/, always with implementation=True (break_distance.my_implementation),
	fragmenting into `size` pieces."""
	plasmid_files = subprocess.check_output("ls -1 syntethic/regenerated",shell=True,text=True)
	files = plasmid_files.split("\n")[:-1]
	
	i=0
	for f in files:
		og = f.split(".1")[0]
		subprocess.call(f"python ./generateShortRead.py /fastas/{og}.1.fna /syntethic/regenerated/{f} {i} {1} {size} True",shell=True)
		i+=1

def generate_syntethic():
	"""func=2 (the definition actually in effect, see note on the earlier
	duplicate above). Picks 30 random plasmids referenced in
	./old_results/allDistances_v2_1.txt and generates a synthetic rearranged
	variant of each via syntethic.run(), at a random fragment count between
	1 and 19."""
	plasmid_pairs = set()
	with open("./old_results/allDistances_v2_1.txt") as f:
		for line in f:
			if "/" in line:
				plasmid_pairs.add("/fastas/"+line.split("/")[2].strip())
				plasmid_pairs.add("/fastas/"+line.split("/")[4].strip())
	k=30
	plasmid = rm.sample(sorted(plasmid_pairs),k)
	for i in range(k):
		nr_of_fragments = rm.randrange(1,20)
		run(plasmid[i],nr_of_fragments)

def run_base_pling_on_syntethic():
	"""func=6. Runs run_pling.run_pling() (base pling, no fragment-order
	sampling) on synthetic plasmids under syntethic/regenerated/, starting
	from index 35 (earlier ones presumably already processed in a prior
	run of this same function)."""
	plasmid_files = subprocess.check_output("ls -1 syntethic/regenerated",shell=True,text=True)
	files = plasmid_files.split("\n")[:-1]
	
	i=35
	for f in range(i,len(files)):
		og = files[f].split("_")
		print(og[0]+og[1])
		run_pling(f"/fastas/{og[0]}_{og[1]}.fna",f"/syntethic/regenerated/{files[f]}",1,1,i)
		i+=1

def strip_path_and_binned(filepath):
    """Extract filename, remove _binned before .fasta"""
    basename = os.path.basename(filepath)
    # remove _binned from the filename
    cleaned = basename.replace('_binned.fasta', '.fasta')
    return cleaned

def generate_ground_truth():
	"""func=7. Reads pairs from real_distances_repaired_pling.txt, strips
	the _binned suffix from each filename, and re-runs generateShortRead.py
	against /plasmid_references/ (the un-binned reference sequences) to
	build a ground-truth distance set to compare binned results against.
	
	The size and implementation variables are taken from the global scope
	"""

	plasmid_pairs = []
 
	
	with open("./real_distances_repaired_pling.txt", 'r') as f:
		for line in f:
			line = line.strip()
			if not line:
				continue
            
			parts = line.split('/')
			# parts = [p + '.fasta' for p in parts if p]  # re-add .fasta
			# if len(parts) != 2:
			# 	print(f"Warning: could not parse line: {line}")
			# 	continue
			
			file1 = strip_path_and_binned(parts[2].split(" ")[0])
			file2 = strip_path_and_binned(parts[4].strip())
			print(file1)
			print(file2)
			plasmid_pairs.append((file1,file2))
	
	i=0
	k=0
	parralel = 1

	while i<len(plasmid_pairs):
		commands = [f"python ./generateShortRead.py /plasmid_references/{j[0]} /plasmid_references/{j[1]} {k} {index} {size} {implementation}" for index,j in enumerate(plasmid_pairs[i:i+parralel])]
		procs = [subprocess.Popen(j,shell=True) for j in commands]
		for p in procs:
			p.wait()
		if not implementation:
			for index,_ in enumerate(plasmid_pairs[i:i+parralel]):
				subprocess.call(f"rm -r ./py_out/input{k}_{index}.txt", shell=True)
				subprocess.call(f"rm -r ./py_out/try{k}_{index}.fasta", shell=True)
		print(f"The batch finished {i}")
		i+=parralel
		k+=1

def run_with_filter():
	"""func=8. Cross-references unique_real_filtered.txt (a filtered plasmid
	pair list, paths under plasmid_references/) against
	unique_distances_real_diff_bin.txt (pairs already available as binned
	fragments) to find the intersection, samples 100 of them, and runs
	generateShortRead.py against the binned_fragments/ versions.
	
	The size and implementation variables are taken from the global scope"""
	plasmid_pairs = []
	plasmid_pairs_that_I_have = []
	with open("unique_distances_real_diff_bin.txt") as f:
		for x in f:
			s = x.strip()
			print(s)
			plasmid_pairs_that_I_have.append(s)

	with open("unique_real_filtered.txt") as f:
		for x in f:
			s = x.strip()
			file1 = s.split()[0][1:].split(".fasta")[0]+"_binned.fasta"
			file2 = s.split()[1][1:].split(".fasta")[0]+"_binned.fasta"

			file1 = file1.replace("plasmid_references","binned_fragments")
			file2 = file2.replace("plasmid_references","binned_fragments")
			if "."+file1+" ."+file2 in plasmid_pairs_that_I_have:
				plasmid_pairs.append((file1,file2))
	i=0
	k=0
	parralel = 10
	plasmid_pairs = rm.sample(plasmid_pairs,100)

	while i<len(plasmid_pairs):
		commands = [f"python ./generateShortRead.py {j[0]} {j[1]} {k} {index} {size} {implementation}" for index,j in enumerate(plasmid_pairs[i:i+parralel])]
		procs = [subprocess.Popen(j,shell=True) for j in commands]
		for p in procs:
			p.wait()
		if not implementation:
			for index,_ in enumerate(plasmid_pairs[i:i+parralel]):
				subprocess.call(f"rm -r ./py_out/input{k}_{index}.txt", shell=True)
				subprocess.call(f"rm -r ./py_out/try{k}_{index}.fasta", shell=True)
		print(f"The batch finished {i}")
		i+=parralel
		k+=1
	
if __name__=="__main__":
	# func selects which experiment to run:
	#   0 sample_random_plasmids       5 sample_random_plasmids2
	#   1 change_fragments_known       6 run_base_pling_on_syntethic
	#   2 generate_syntethic           7 generate_ground_truth
	#   3 run_syntethic                8 run_with_filter
	#   4 sample_continous          other trying_something (fallback)
	func = int(sys.argv[1])
	size = int(sys.argv[2])
	implementation = sys.argv[3].lower()== "true"
	if func == 0:
		sample_random_plasmids()
	elif func==1:
		change_fragments_known(size,implementation)
	elif func==2:
		generate_syntethic()
	elif func==3:
		run_syntethic(size)
	elif func==4:
		sample_continous(implementation)
	elif func==5:
		sample_random_plasmids2(size,implementation)
	elif func==6:
		run_base_pling_on_syntethic()
	elif func==7:
		generate_ground_truth()
	elif func==8:
		run_with_filter()
	else:
		trying_something()
